### ISSUE TITLE
API Key Authentication : 401

### ISSUE THREAD

**Issue by bensonik** [qlands/formshare_sql_plugin#1]
unable to authenticate using my apikey_secret, does this method work with a standard formshare.org account?

```
import json
import requests

url = "https://formshare.org/"

login_dict = {
    "X-API-Key": "xxxxxxx",
    "X-API-Secret": "xxxxx",
}
headers = {"Content-type": "application/json", "Accept": "text/plain"}
r = requests.post(
    url + "/api/1/security/login", data=json.dumps(login_dict), headers=headers
)

r.json()
{'status': '401', 'error': 'Such API key does not exist.'}
```
Benson

**Comment by bensonik** [comment]
Thanks Carlos,
I followed the exact steps to get my API credentials and got the error.

Both in R & Python the request keeps on asking for the X-API-Key and X-API-Secret even after providing the credentials

**Comment by qlands** [comment]
I just ran this example and it works with my API key and secret.

```
import json
import requests

url = "https://formshare.org/"

login_dict = {
    "X-API-Key": "my_key",
    "X-API-Secret": "my_secret_that_I_generated_and_saved",
}
headers = {"Content-type": "application/json", "Accept": "text/plain"}
r = requests.post(
    url + "/api/1/security/login", data=json.dumps(login_dict), headers=headers
)

print(r.json())
#{'status': '200', 'result': {'token': '9725e152db563e7f3c049fed2b82c33e', 'expires_on': '2023-08-18 18:11:47.046579'}}
```

Just to confirm. You are using the key and secret of your **FormShare user** not of an assistant.

**Comment by bensonik** [comment]
I was skipping  a very crucial step:  a click on the `Change key or Secret` to update the credentials on FormShare
